// <auto-generated />
using System;
using InvoiceSample.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceSample.Persistence.Migrations
{
    [DbContext(typeof(InvoiceSampleDbContext))]
    [Migration("20241016232126_FixInvoiceReference")]
    partial class FixInvoiceReference
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvoiceSalesOrder", b =>
                {
                    b.Property<Guid>("InvoicesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SalesOrdersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InvoicesId", "SalesOrdersId");

                    b.HasIndex("SalesOrdersId");

                    b.ToTable("InvoiceSalesOrder");
                });

            modelBuilder.Entity("InvoiceSample.Persistence.Tables.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GrossValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("State")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("VatValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Number");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("InvoiceSample.Persistence.Tables.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GrossValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("NetValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid?>("SalesOrderLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("VatRate")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("VatValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("WarehouseReleaseLineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("SalesOrderLineId");

                    b.HasIndex("WarehouseReleaseLineId");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("InvoiceSample.Persistence.Tables.InvoiceVatSum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GrossValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("NetValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("VatRate")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("VatValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceVatSums");
                });

            modelBuilder.Entity("InvoiceSample.Persistence.Tables.SalesOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoInvoice")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ServiceLinesInvoiced")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("InvoiceSample.Persistence.Tables.SalesOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GrossValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsService")
                        .HasColumnType("bit");

                    b.Property<decimal>("NetValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("SalesOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("VatRate")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("VatValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("SalesOrderLines");
                });

            modelBuilder.Entity("InvoiceSample.Persistence.Tables.WarehouseMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("SalesOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("WarehouseMovements");
                });

            modelBuilder.Entity("InvoiceSample.Persistence.Tables.WarehouseMovementLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GrossValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid?>("SalesOrderLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("VatRate")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("VatValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("WarehouseMovementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SalesOrderLineId");

                    b.HasIndex("WarehouseMovementId");

                    b.ToTable("WarehouseMovementLines");
                });

            modelBuilder.Entity("InvoiceSalesOrder", b =>
                {
                    b.HasOne("InvoiceSample.Persistence.Tables.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceSample.Persistence.Tables.SalesOrder", null)
                        .WithMany()
                        .HasForeignKey("SalesOrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceSample.Persistence.Tables.InvoiceLine", b =>
                {
                    b.HasOne("InvoiceSample.Persistence.Tables.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceSample.Persistence.Tables.SalesOrderLine", "SalesOrderLine")
                        .WithMany()
                        .HasForeignKey("SalesOrderLineId");

                    b.HasOne("InvoiceSample.Persistence.Tables.WarehouseMovementLine", "WarehouseReleaseLine")
                        .WithMany()
                        .HasForeignKey("WarehouseReleaseLineId");

                    b.Navigation("Invoice");

                    b.Navigation("SalesOrderLine");

                    b.Navigation("WarehouseReleaseLine");
                });

            modelBuilder.Entity("InvoiceSample.Persistence.Tables.InvoiceVatSum", b =>
                {
                    b.HasOne("InvoiceSample.Persistence.Tables.Invoice", "Invoice")
                        .WithMany("VatSums")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceSample.Persistence.Tables.SalesOrderLine", b =>
                {
                    b.HasOne("InvoiceSample.Persistence.Tables.SalesOrder", "SalesOrder")
                        .WithMany("Lines")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("InvoiceSample.Persistence.Tables.WarehouseMovement", b =>
                {
                    b.HasOne("InvoiceSample.Persistence.Tables.SalesOrder", "SalesOrder")
                        .WithMany("WarehouseReleases")
                        .HasForeignKey("SalesOrderId");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("InvoiceSample.Persistence.Tables.WarehouseMovementLine", b =>
                {
                    b.HasOne("InvoiceSample.Persistence.Tables.SalesOrderLine", "SalesOrderLine")
                        .WithMany()
                        .HasForeignKey("SalesOrderLineId");

                    b.HasOne("InvoiceSample.Persistence.Tables.WarehouseMovement", "WarehouseMovement")
                        .WithMany("Lines")
                        .HasForeignKey("WarehouseMovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesOrderLine");

                    b.Navigation("WarehouseMovement");
                });

            modelBuilder.Entity("InvoiceSample.Persistence.Tables.Invoice", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("VatSums");
                });

            modelBuilder.Entity("InvoiceSample.Persistence.Tables.SalesOrder", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("WarehouseReleases");
                });

            modelBuilder.Entity("InvoiceSample.Persistence.Tables.WarehouseMovement", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
